encuestas/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'encuestas'
urlpatterns = [
    #Catálogo de redes sociales
    path('redsocial/create/', RedSocialCreateView.as_view(),name='red-create'),
    path('redsocial/list/', RedSocialListView.as_view(),name='red-list'),
    path('redsocial/<pk>/update/', RedSocialUpdateView.as_view(),),

    path('create/', EncuestaCreateView.as_view(),name='encuesta-create'),
    path('estadisticas/list/', EstadisiticasListView.as_view(),name='estadistica-list'),
]

pruebaemqu/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from rest_auth import urls as urls_rest

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', urls_rest.LoginView.as_view()),   
    path('api/encuestas/', include('encuestas.urls')),
]

encuestas/models.py
from django.db import models

# Create your models here.

class RedesSocialesCatalogo(models.Model):
    descripcion = models.CharField(max_length=100, null=True)

    class Meta:
        db_table = 'redessocialescatalogo'

class Encuesta(models.Model):
    correo = models.CharField(max_length=100, null=True)
    edad = models.IntegerField( null=True)
    sexo = models.CharField(max_length=100)
    fecha = models.DateField(null=True,blank=True)

    class Meta:
        db_table = 'encuesta'

class Pregunta(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.PROTECT, null=True)
    redSocial = models.ForeignKey(RedesSocialesCatalogo, on_delete=models.PROTECT, null=True)
    isFavorita = models.BooleanField(default = 0)
    tiempo = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'pregunta'

encuestas/views.py
from django.shortcuts import render

encuestas/views/encuestasViews.py
from asyncio.base_subprocess import ReadSubprocessPipeProto
from re import S
from django.forms import FloatField, TimeField
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.generics import DestroyAPIView, ListAPIView,CreateAPIView,RetrieveAPIView,UpdateAPIView, GenericAPIView
from rest_framework import status, authentication, permissions
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.views import APIView
from encuestas.serializers import *
from django.shortcuts import render, redirect
from django.db.models import Avg, Count, Sum, F
from django.db.models import TimeField, DateTimeField

from datetime import datetime
# Create your views here.

class EncuestaCreateView(APIView):
    permission_classes=(permissions.AllowAny,)
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'encuesta.html'

    def get(self, request):
        serializer=EncuestasSerializer
        redes = RedesSocialesCatalogo.objects.all()
        return Response({'serializer':serializer, 'redes':redes})

    def post(self, request):
        try:
            correo=request.POST.get('correo')
            edad= request.POST.get('edad')
            sexo = request.POST.get('sexo')
            fecha = datetime.now()
            encuesta = Encuesta(correo=correo,edad=edad,sexo=sexo,fecha=fecha)
            encuesta.save()
            redes=request.POST.getlist('redSocialId')
            tiempos = request.POST.getlist('tiempo')
            try:
                for red in redes:
                    posicion= redes.index(red)
                    favorita=0
                    if int(request.POST.get('isFavorita'))==int(red):
                        favorita= 1
                    pregunta = Pregunta(encuesta_id=encuesta.id,redSocial_id=red,isFavorita=favorita,tiempo=tiempos[posicion])
                    pregunta.save()
            except:
                return Response({"response" : "Error en creación de encuesta"}, status = status.HTTP_400_BAD_REQUEST)
        except:
            return Response({"response" : "Error en creación de encuesta"}, status = status.HTTP_400_BAD_REQUEST)

        return redirect('encuestas:estadistica-list')

def obtenerFavoritoEdad(red):
    rangos={
    "18-25 años": Pregunta.objects.filter(redSocial_id=red.id, isFavorita=1,encuesta__edad__range=[18,25]).count(),
    "26-36 años": Pregunta.objects.filter(redSocial_id=red.id, isFavorita=1,encuesta__edad__range=[26,36]).count(),
    "34-40 años": Pregunta.objects.filter(redSocial_id=red.id, isFavorita=1,encuesta__edad__range=[34,40]).count(),
    "40 + años": Pregunta.objects.filter(redSocial_id=red.id, isFavorita=1,encuesta__edad__gt=40).count(),
    }
    max=0
    favorito=None
    for rango in rangos:
        if int(rangos[rango])>max:
            favorito=rango
    
    return favorito


class EstadisiticasListView(APIView):
    permission_classes = [permissions.AllowAny,]
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'estadisticas.html'
    def get(self, request):
        redes=[]
        countFavorita=0
        
        redFavorita=None
        countNoFavorita=0
        redNoFavorita=None
        for red in RedesSocialesCatalogo.objects.all():
            promedio=None
            average = Pregunta.objects.filter(redSocial_id=red.id).aggregate(tiempo_avg=(Avg('tiempo')))
            
            favorita= Pregunta.objects.filter(redSocial_id=red.id, isFavorita=1).count()
            if favorita>=countFavorita:
                countFavorita=favorita
                redFavorita=red.descripcion
            
            noFavorita= Pregunta.objects.filter(redSocial_id=red.id, isFavorita=0).count()
            if noFavorita>=countNoFavorita:
                countNoFavorita=noFavorita
                redNoFavorita=red.descripcion
            if average["tiempo_avg"] != None:
                promedio= round(average["tiempo_avg"],2)
            redes.append({
                "redSocial":red.descripcion,
                "promedio":promedio,
                "favorita":favorita,
                "noFavorita":noFavorita,
                "rangoFavorito":obtenerFavoritoEdad(red)
            })
       
        estadistica={
            "encuesta": Encuesta.objects.count(),
            "favorita": redFavorita,
            "noFavorita": redNoFavorita,
            "redes": redes 
        }
        return Response({'content': estadistica}, status = status.HTTP_200_OK)

encuestas/views/redesSocialesViews.py
from http.client import OK
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import DestroyAPIView, ListAPIView,CreateAPIView,RetrieveAPIView,UpdateAPIView
from rest_framework import status, authentication, permissions
from encuestas.serializers import *
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import render, redirect
# Create your views here.

class RedSocialCreateView(CreateAPIView):
    permission_classes = [permissions.AllowAny,]
    serializer_class = RedesSocialesCatalogoSerializer


class RedSocialListView(ListAPIView):
    queryset = RedesSocialesCatalogo.objects.all()
    permission_classes = [permissions.AllowAny,]
    serializer_class = RedesSocialesCatalogoSerializer
    

class RedSocialUpdateView(UpdateAPIView):
    queryset = RedesSocialesCatalogo.objects.filter()
    permission_classes=(permissions.AllowAny,)
    serializer_class = RedesSocialesCatalogoSerializer
    http_method_names = ['put']

encuestas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        <h2><a href="{% url 'encuestas:encuesta-create'%}">Crear Encuesta</a></h2>
        <h2><a href="{% url 'encuestas:estadistica-list'%}">Estadísticas</a></h2>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

encuestas/templates/encuesta.html
{% extends 'base.html' %}

{% block content %}
{% load rest_framework %}
{% load static %}

<style type="text/css">
    .boton_1{
        border: none; /* Remove borders */
        color: white; /* Add a text color */
        padding: 14px 28px; /* Add some padding */
        cursor: pointer; /* Add a pointer cursor on mouse-over */
        background-color: #2196F3;
        background: #0b7dda;
    }
    .li_1{
        color: #2196F3;
    }
</style>
<form action="{% url 'encuestas:encuesta-create'%}" method="POST">
    {% csrf_token %}
    <h1>Encuesta</h1>
    {% render_form serializer %}

        <ul>
            <label>*Por favor dinos cual es el tiempo promedio por día que la pasas en las siguientes redes sociales.
            </label>
            <label>*Por favor selecciona solamente una red social favorita.
            </label>
            {% for red in redes %}
            <li class="li_1">{{ red.descripcion }}</li>
            <input type="hidden" value={{ red.id }} id="redSocialId", name="redSocialId">
            <label>Tiempo</label>
            <input type="text" value="00:00" pattern="[0-9]{2}:[0-9]{2}" id="tiempo" name="tiempo">
            <label>Favorita</label>
            <input type="checkbox" value={{ red.id }} id="isFavorita" name="isFavorita"> 
            {% endfor %}
        </ul>
    <input type="submit" value="Save" class="boton_1">
</form>


{% endblock %}

encuestas/templates/estadisticas.html
{% extends 'base.html' %}

    {% block content %}
    <h1>Estadísticas</h1>
    <ul>
        {% csrf_token %}
        <label>No. Encuestas: {{ content.encuesta }}</label>
        <br>
        <label>Red Social Favorita: {{ content.favorita }}</label>
        <br>
        <label>Red Social Menos Favorita: {{ content.noFavorita }}</label>
            {% for r in content.redes %}
            <br>
            <br>
                <label>{{ r.redSocial }}</label>
                <br>
                <label>Promedio de tiempo:{{ r.promedio }}</label>
                <br>
                <label>Rango de edad que la prefiere:{{ r.rangoFavorito }}</label>
            {% endfor %}
        
    
    </ul>
    {% endblock %}

    